version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /mnt/resume-volume/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - webnet
  server:
    image: mykytaproks/resume_server:${TAG}
    restart: unless-stopped
    command: sh -c "poetry run python manage.py createsu && poetry run uwsgi --ini uwsgi.ini"
    volumes:
      - /mnt/resume-volume/static:/www/static
      - uwsgi_socket:/www/socket
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DOMAIN=${DOMAIN}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    depends_on:
      - db
    networks:
      - webnet
  frontend:
    image: mykytaproks/resume_frontend:${TAG}
    restart: unless-stopped
    command: node build
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    networks:
      - webnet
  nginx:
    image: mykytaproks/resume_nginx:${TAG}
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/resume-volume/static:/www/static
      - uwsgi_socket:/www/socket
      - /mnt/resume-volume/letsencrypt:/etc/letsencrypt
    depends_on:
      - server
      - frontend
    networks:
      - webnet
volumes:
  uwsgi_socket:

networks:
    webnet: