# Generated by Django 5.0.2 on 2024-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_invitecode_userprofile_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                default="n3KiHgGWiMa0Pwct", editable=False, unique=True
            ),
        ),
    ]
