# Generated by Django 5.0.2 on 2024-03-03 12:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_invitecode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                default=core.models.get_invite_code, editable=False, unique=True
            ),
        ),
    ]
