# Generated by Django 5.0.2 on 2024-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_invitecode_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="updates_active",
            field=models.BooleanField(default=True),
        ),
    ]
