# Generated by Django 5.0.2 on 2024-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="interval",
            field=models.CharField(default="1d", max_length=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="period",
            field=models.CharField(default="6mo", max_length=10),
        ),
    ]
