# Generated by Django 5.0.2 on 2024-03-23 13:01

import django.db.models.deletion
import stocks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_stock_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="state",
        ),
        migrations.AddField(
            model_name="subscription",
            name="interval",
            field=models.CharField(default="1d", max_length=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="period",
            field=models.CharField(default="6mo", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("stock", "period", "interval")},
        ),
        migrations.AddField(
            model_name="subscription",
            name="state",
            field=models.ForeignKey(
                default=stocks.models.default_state,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="stocks",
                to="stocks.state",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="users",
            field=models.ManyToManyField(
                related_name="subscriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
    ]
