name: Deploy Server

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/resume_server:${{ github.ref_name }} ./server

    - name: Tag Docker image
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/resume_server:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/resume_server:latest
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/resume_server:${{ github.ref_name }}

    - name: Push latest
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/resume_server:latest