name: Python CI

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ] 

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v3
        # Set up Python
        -   name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11' 
        # Install dependencies
        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install flake8 mypy poetry poetry-plugin-export
                cd server
                poetry install --dev
                poetry export -f requirements.txt --output requirements.txt --dev --without-hashes
                cat requirements.txt
                pip install -r requirements.txt

        # # Run Flake8
        # -   name: Lint with Flake8
        #     run: |
        #         # Stop the build if there are Python syntax errors or undefined names
        #         flake8 server --count --select=E9,F63,F7,F82 --show-source --statistics
        #         # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #         flake8 server --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        # Run MyPy
        -   name: Type check with MyPy
            run: |
                cd server
                mypy .
